/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations, useFBX } from "@react-three/drei";

export function Avatar(props) {
  const group = useRef();
  const { nodes, materials } = useGLTF("models/Character.glb");

  const { animations: thankfulAnimation } = useFBX("animations/Thankful.fbx");

  thankfulAnimation[0].name = "Thankful";

  const { actions } = useAnimations(thankfulAnimation, group);

  useEffect(() => {
    actions["Thankful"].reset().play();
  }, []);

  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation-x={-Math.PI / 2}>
        <group name="Scene">
          <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
            <skinnedMesh
              name="Ch03"
              geometry={nodes.Ch03.geometry}
              material={materials.Ch03_Body}
              skeleton={nodes.Ch03.skeleton}
            />
            <primitive object={nodes.mixamorigHips} />
          </group>
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("models/Character.glb");
